CREATE DATABASE	CPL_DB

USE CPL_DB

CREATE TABLE VENDOR(
	VENDOR_ID			INT	NOT NULL UNIQUE, 
	VENDOR_NAME			VARCHAR(50),	
	VENDOR_STREET		VARCHAR(50),	
	VENDOR_CITY			VARCHAR(50),
	VENDOR_ZIP			VARCHAR(20),
	VENDOR_COUNTRY		VARCHAR(20),
	VENDOR_PHONE		VARCHAR(50),		
	VENDOR_CONTACT		VARCHAR(50),
	VENDOR_DESCRIPT		VARCHAR(100),
	VENDOR_EMAIL		VARCHAR(50),
	VENDOR_STATUS		VARCHAR(20),
	PRIMARY KEY (VENDOR_ID));

CREATE TABLE CONTRACT(
	VENDOR_ID			INT ,
	CONTRACT_ID			INT NOT NULL UNIQUE,
	CONTRACT_TYPE		VARCHAR(50),							
	PRIMARY KEY (VENDOR_ID, CONTRACT_ID),		
	FOREIGN KEY (VENDOR_ID)); 

CREATE TABLE PRODUCT(
	PRODUCT_ID		INT	NOT NULL	UNIQUE,
	PRODUCT_NAME		VARCHAR(50),
	PRODUCT_PARENT_ID	INT,
	PRODUCT_DESC		VARCHAR(100),
	PRODUCT_EST_PRICE	INT,					
	PRIMARY KEY (PRODUCT_ID));						

CREATE TABLE ORDER(
	ORDER_ID			INT	NOT NULL, UNIQUE,
	VENDOR_ID,			INT
	EMPLOYEE_ID,			INT
	ORDER_DATE,			VARCHAR(50)
	PRIMARY KEY (ORDER_ID),
	FOREIGN KEY (VENDOR_ID),
	FOREIGN KEY (EMPLOYEE_ID)); 

CREATE TABLE ORDER_ITEM(
	PRODUCT_ID			INT,
	ORDER_ID,			INT,
	ORDER_ITEM_QUAN		INT,
	PRIMARY KEY (PRODUCT_ID, ORDER_ID),
	FOREIGN KEY (PRODUCT_ID)
	FOREIGN KEY (ORDER_ID)); 

CREATE TABLE INVOICE

CREATE TABLE EMPLOYEE

CREATE TABLE PAYMENT

CREATE TABLE PAY_SOURCE 

CREATE TABLE FUNDING 
