--Query 1

CREATE PROCEDURE GetUnpaidPastDueInvoice
	@VendorName	VARCHAR(255)
AS

SELECT		v.VENDOR_NAME,
			i.INVOICE_ID, 
			i.INVOICE_AMT,
			i.INVOICE_DUE_DATE,
			i.INVOICE_STATUS
FROM		INVOICE i LEFT JOIN PAYMENT p ON i.INVOICE_ID = p.INVOICE_ID
			JOIN VENDOR v ON i.VENDOR_ID = v.VENDOR_ID
WHERE		p.INVOICE_ID IS NULL 
			AND	i.INVOICE_DUE_DATE < GETDATE() 
			AND	v.VENDOR_NAME = @VendorName

EXECUTE GetUnpaidPastDueInvoice 'Lynda'
